### ISSUE TITLE
First Challenge

### ISSUE THREAD

**Issue by MOJTABAFA** [quinngroup/ToxoPlasma#1]
@magsol 
The first challenge is **how to convert the Avi files to Data matrices for python ?** I already check the Internet but unfortunately the only offer is "pymedia" which is not updated for a long time and it's not compatible with new version of python and ubuntu. do you know any solution for this problem ?

**Comment by magsol** [comment]
Use OpenCV to read from AVI files into Numpy arrays. 

iPhone'd

**Comment by MOJTABAFA** [comment]
I already tried a lot to install the Opencv for python, Finally the last version which I could install it is Opencv 2.4.11 in anaconda ( I dont know why this version installed by conda instruction maybe it's compatible with my current python version which is 2.7 and also numpy and scipy version). I also installed ffmpeg 2.7.0 via conda instruction. to check if I can get the avi file correctly, I used the following code :
```javascript
import cv2
path = '/home/targol/anaconda2/lib/python2.7/'
video = '615.avi'   # one of the videos in bluedata cluster
print (path + video)
vid = cv2.VideoCapture(path + video)
result = vid.isOpened()
print result
print cv2.__version__
```
my out put for above code is as follows :
`/home/targol/anaconda2/lib/python2.7/615.avi`
`False`
`2.4.11`
`[Finished in 0.2s]`
I don't know why but always my out put is 'False' , meaning that the file is not opened. Do you have any idea about that ?

**Comment by magsol** [comment]
Have you tried googling around?

iPhone'd

**Comment by MOJTABAFA** [comment]
Yes of course I did . There were some problems like what I experienced but the proposed solutions does not solved my problem. 
I already tried 2 ways to install OpenCv : 
1- installing the latest version of that normally through the console instructions and installing it's dependencies : after several tries finally it is installed  without errors but in Python It couldn't recognize the cv2 library.Thus, I tried the 2nd solution.
2- I installed the OpenCv and ffmpeg through anaconda , now the python can import the cv2 but there exists the above mentioned problem.
Any way, Now, I'm trying to do it from other ways and will let you know if still there were some problems existed.

**Comment by svella21790** [comment]
When we make the movies they are usually in a .czi file format.  This is the default extension that the microscope uses, and I converted the movies to a .avi file extension. When it comes to writing the script for the program in the future, I could convert them to different file extension if it is easier. Would a .mov file extension be easier?  We are very much a mac friendly lab.
