### ISSUE TITLE
Comments for "Result Video Link"

### ISSUE THREAD

**Issue by svella21790** [quinngroup/ToxoPlasma#10]
Hey Mojtaba,

From the latest results, the tracking looks promising, but we are still faced with some issues.

1.) We want to keep the number of starting tracks the same as the number of final ending tracks.  It appears that the script is detecting more or new cells as the video progresses.  This will affect the final result, so ideally we want to start tracking a cell from the start of the movie to the end without any breaks in its tracking. That being said, we DO NOT need every single cell in a video quantified, so if there is only a certain number of cells in each video with a clear tracking path, those will suffice.

2.) The detection algorithm is still having some problems with clumped cells such that it is detecting them as one lump sum.  Would it be possible to constrain the size of the detection algorithm to match the approximate size of our cells?  Or in need be you can ignore clumped cells and not have them detected/quantified/tracked or whatever; just focus on the single cells that are easily quantifiable.

Hope this helps,
Stephen

**Comment by magsol** [comment]
1: Absolutely agree. We never intended to have the object count fluctuate in the final result; seeing it was just a way of helping us determine where our initial methods were getting it wrong, and to give us a better idea of how to make them more robust.

2: This is a hard problem for sure, but I'd like to think that, at some point in the video, the objects aren't clumped. If we can tune our algorithm to identify "ideal" representations of each object at some point in the video and then backtrace it through the whole video, that would help disambiguate the clumps. 

iPhone'd

**Comment by MOJTABAFA** [comment]
@svella21790 @magsol 
Thank you for your comments, let me see what can I do. I'm working on issues and will let you know the results soon.
