### ISSUE TITLE
Object Tracking 

### ISSUE THREAD

**Issue by MOJTABAFA** [quinngroup/ToxoPlasma#3]
@magsol 
Dear Dr. Quinn, 
Finally I did some _object tracking_ in our file. :) 
My code is already pushed into current repository. Also I wrote the resulting video in an **avi** file and saved it in "**Object Tracking results video!**" folder. For running the code, please use the original video from "**result for code 2**" folder with -v switch in command line. 

Please take a look on my results and let me know about the result of your consideration.

**Comment by magsol** [comment]
Excellent work! Great first step. We clearly have the machinery to perform object tracking.

The next step is to see if we can improve the robustness. I noticed you put in a hard threshold on the area of the located objects, ignoring objects whose area was below 200. We'll need something more sophisticated, as the objects may be small but we also want to make sure we're not tracking noise.

Furthermore, the fluorescence of the objects can change. You may have noticed certain points in the video where the relative fluorescence of the objects flashes briefly; this is a controlled addition of calcium signaling agents, which the fluorescent marker responds to. We'll need to be able to account for this in our tracking algorithm.

A good first step would be preprocessing--along the lines of what you were trying, it would seem: thresholding out noise so we have a constant background against which to track objects, which should make it easier to see them across frames.

**Comment by magsol** [comment]
Also, this doesn't have to happen now, but at some point we'll need to clean up the code... :)

**Comment by MOJTABAFA** [comment]
@magsol 
dear Dr. Quinn
Thanks for your positive and constructive comments. yes, I do agree that the threshold is hard but considering the point that our frame size is 1024 x 1024 , the area size of 20 is not so much. actually I did not get your mean by more sophisticated method. is it possible to explain men more what sophisticated function we need? As of now till we have to distinguish between florescent greens and normal greens and we do not have any thing else to discriminate the objects our work is a bit difficult. any way, I'm testing several methods and approach to get better results, but if you have any idea to navigate me please let me know.

**Comment by MOJTABAFA** [comment]
sorry it was a mistake I mean the area size of 200  :)

**Comment by magsol** [comment]
You need to find a way to make the objects we're tracking more coherent across frames. Since you didn't commit the code that created the new video I can't see what you've done differently, but judging from the video the threshold is *too* hard--it's occasionally cutting out the objects we're interested in.

Part of tracking is identifying an object in one frame, and then associating it with an object in the *next* frame. The next step is making your current tracking algorithm more robust in that sense--it should be able to follow an object across several frames, and be able to UNIQUELY IDENTIFY it as the **same** object. That way, we can track and parameterize its trajectory across the entire video.

**Comment by MOJTABAFA** [comment]
@magsol 
Thanks for your nice comments , two more questions which is still vague for me is about the florescent objects :
1. what reason makes those objects florescent? to me, It seems that we're dealing with a 2D movie of a 3D reality and when the objects are moving across "Z" vector (or depth) and approaching the XY plain, they looks florescent and when they are departing the XY plain they looks more darker. If this theory would be correct all the objects are florescent but moving in different level of depth. In this case what's the added value of tracking ?is there any relationship between the intensity of an object and that premised depth ? 
2. why in some part of movies suddenly a large number of objects are getting florescence? is it a witness to the fact that all the objects are florescent or it's because of some other reasons (like injecting some liquids or etc. ) if not it would be a big noise for tracking. 

sorry for asking a lot of question, but those are the vague points in my mind and clearing them will help me better understanding and as a consequence better solution.

**Comment by magsol** [comment]
1: I don't fully follow this question, but you should read through Dr. Silvia Moreno's research summery: http://cellbio.uga.edu/directory/faculty/silvia-nj-moreno 

2: I answered this question in our Slack discussion, and more concretely in [my previous response in this thread](https://github.com/quinngroup/ToxoPlasma/issues/3#issuecomment-220641706): 

```
Furthermore, the fluorescence of the objects can change. You may have noticed certain points in the video where the relative fluorescence of the objects flashes briefly; this is a controlled addition of calcium signaling agents, which the fluorescent marker responds to. We'll need to be able to account for this in our tracking algorithm.
```

**Comment by MOJTABAFA** [comment]
@magsol 
Dear Dr. Quinn : I want to draw the tracking trajectory for our code , for this purpose as I know we must find the centre of every object which is possible through following code (for every frame) :
```javascript
import cv2
import numpy

img = cv2.imread('toxop.jpg', 0)
_, contours, _ = cv2.findContours(img.copy(), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_L1)
print len(contours)
centres = []
for i in range(len(contours)):
    moments = cv2.moments(contours[i])
    M = int(moments['m00'])
    if M != 0 :
        centres.append((int(moments['m10']/moments['m00']), int(moments['m01']/moments['m00'])))
    #print type(M)
    #print M
    
print centres

cv2.imshow('image', img)
cv2.imwrite('output.png',img)
cv2.waitKey(0)
```
this code makes a list of center points of every region ( object) in the frame. By applying the our mask and roi we will have the center of florescet objects . and we have to connect the points in different frames together and this point is my confusing point, would you please help me to draw the trajectory ? 
Thanks

**Comment by magsol** [comment]
One option would be to maintain a matrix in the background of the same spatial dimensions as the video, filling in the pixels to represent the trajectories. 

iPhone'd
