### ISSUE TITLE
Parameters for Tracking

### ISSUE THREAD

**Issue by svella21790** [quinngroup/ToxoPlasma#4]
Hey all,

I am the student in the Moreno lab who made the motility videos.  I just have a couple quick questions and comments. 

Great work so far! I just saw the video, and it looks very promising.  If you notice in the videos, that there is a large increase in fluorescence about halfway in between the video and subsequently an increase in the motility.   This increase is usually due to the addition of calcium or some agonist that causes cytosolic levels of calcium to increase. Our cells are expressing a special chromophore called GCaMP that is sensitive to calcium and will increase its fluorescence.   

What we are looking to do is quantify the movement after the addition of calcium or the agonist. Ideally, the parameters that we would like to quantify are the velocity (speed), distance, circular motion (rotational speed), and the finally relate these all back to the fluorescence profile (calcium oscillations). Simply put, we are looking to identify an oscillation pattern in response to motility. Would the program be able to export the fluorescence profile of the tracks into an excel file or something equivalent?

Also for curiosity, what parameters are you guys currently using to detect and track the cells? 

Thanks,
Stephen

**Comment by magsol** [comment]
Hi Stephen, thanks for the comment.

@MOJTABAFA can speak more to the specifics of the current tracking methods, but what we're essentially doing (for the moment, let's see what we get) is to represent each object as its center of mass. That makes it easy to track distance (and therefore speed) and fluorescence (as a function of time). Circular motion will be a bit trickier but I'm thinking there are parametric models that would simplify this process, based essentially on a retrospective analysis using the raw trajectory of the object.

Once we have these numbers, we can then query the time series to perform before/after the addition of the agonist. We can do blunt averages of these statistics, but I'd also like to feed them into time series models (e.g. ARMA) and observe the evolution of the parameters in those models in response to the agonist.

**Comment by MOJTABAFA** [comment]
Hi Stephen, Thank you very much for your comments and contribution. 
Now, I think Dr. Quinn answered most of your questions. There are some points about current tracking method. Actually there are several methods to do the tracking, but the tracking problem is absolutely a subjective issue. In different domain with different type of objects we have to follow its appropriate methodology. In current project, as Dr.Quinn mentioned, we're dealing with the center of mass of each object. At first we're trying to discriminate the fluorescence objects from the non fluorescence ones in video (based on the pixel intensities). After that by finding the appropriate contours of those specific regions we're trying to find the ROI ( region of image ) for each fluorescence object and track it in all entire frames. Now we're working to draw the "Tracking Trajectory" to show it in the video and quantify it for some specific purposes that already Dr. Quinn explained. 
After all, we will be able to save the quantified information in a Data format.  Please let me know if you need more detailed information.
Thanks
Mojtaba

**Comment by magsol** [comment]
@svella21790:

Have a look at Mojtaba's latest video, "goodsegtracking.avi". @MOJTABAFA, please point Stephen to the Google Drive link where you're storing the videos.

Also see ticket #7 for our latest discussion on further improvements. I think we're already getting to the stage where we can have some initial results (see my final point on that ticket about overlaying the various trajectories).

When is that conference you and Dr. Moreno wanted to submit to?

**Comment by svella21790** [comment]
Hey Dr. Quinn. 

Abstracts for the conference are due on July 11th, but the conference itself isn't until September 22nd. That should buy some time.

**Comment by magsol** [comment]
Very cool. May have some interesting things to say by then.

**Comment by svella21790** [comment]
I found the video! Very very impressive!!!! Seems very promising so far! :)

**Comment by MOJTABAFA** [comment]
@svella21790
Thank you very much for your comments, I want to remove the video files from repository but the google drive is already available on a txt file in our repository, from now on, you can check the links to see the latest results. 
@magsol
Your pieces of advice seems extremely remarkable but let me think about them and explore your mentioned points till tomorrow, then I'll discuss them with you :)
