### ISSUE TITLE
Video segmentation 

### ISSUE THREAD

**Issue by MOJTABAFA** [quinngroup/ToxoPlasma#6]
@magsol
Only FYI : I already tried to do segmentation on video to see if this technique could be able to help us to achieve better preprocessing for a robust tracking algorithm or not. I already uploaded the code and some video results in " other results" folder.

**Comment by magsol** [comment]
Since I'm at a conference all week, could you give me the highlights / summarize your findings?

**Comment by MOJTABAFA** [comment]
@magsol
Yeah sure, but since I'm working now in another technique as a complement for our segmentation let me do something more and summarize them, then I think tonight or tomorrow morning will send you a full report.
