### ISSUE TITLE
The problem of area of the frame

### ISSUE THREAD

**Issue by MOJTABAFA** [quinngroup/ToxoPlasma#7]
@magsol 
As you can see in new videos, in tracking we have 2 major problems : _**very small tracking frames**_ and **_very large tracking frames._** 
_The problem with very large frame is :_ sometimes we can see the objects are too close together , as a consequence the "tracker" will assume all these 2 or 3 objects as a big object inside a tracking frame which makes serious problems. I tried to make some distance between close regions by using some filters but sometimes in our original video the objects are too close together and in some frames they have some intersection together which makes them **inseparable**.  
_The second problem is the small frames_ which are appearing because of different pixel intensities in an object . This problem is not so serious unless we faced with nested frames in an object. 
I started to read some papers and solutions for both the problems. I think one solution is to find the standard area of objects +/- K% ( since the area of objects are approximately equal) . still I'm searching and thinking for a creative idea for this issue , please let me know if you have any comment about this issue.

**Comment by magsol** [comment]
Took a glance at `goodsegtracking.avi`; looks like we're on the right path. Still a lot of work to do, though.

- Can you try *uniquely identifying* each trajectory? Right now you're coloring the trajectories of the objects and that's great, but let's see if we can assign each unique trajectory a different color. That will give us a better idea of what our algorithm considers a single coherent trajectory, and which objects it loses track of and then re-tracks later (but identifies as a different object, even though it's still the same one).
 - In that vein: how many objects are we even tracking? What does this number look like as a function of time? Is there a way to provide an estimate of the number of objects at any given time and try to constrain our object-finding algorithm based on that number?
 - Another idea for more robustly tracking objects--I don't really see any case where objects disappear or new objects appear halfway through a video. Put another way, the number of objects in a given video is **constant**. We can take advantage of this: if our tracking algorithm picks up a new object halfway through the video, or loses an object halfway through, we know the object is still there (or was always there); it's just a matter of tweaking our algorithm's sensitivity in a narrow space at a very specific time. For example, if we're tracking an object the first few frames and then lose it on the next frame, we know the object is likely still there but just got too dark; we can try to adjust the threshold parameters on-the-flly until we see it again.
 - Even without all these fixes, it would be interesting to start overlaying these trajectories on top of each other. It seems like we already have some distinct motion patterns arising from the video. Can we "normalize" these trajectories somehow to allow for a more direct comparison (without fully parameterizing them)? For example, I'm thinking of basically translating their spatial dimensions so they all start from the exact same point before then allowing the objects to move. That way, we can more directly compare the paths each one takes.
