### ISSUE TITLE
Plotting the "Number of objects" and "Number of fluorescent objects" per frame 

### ISSUE THREAD

**Issue by MOJTABAFA** [quinngroup/ToxoPlasma#8]
@magsol 
Dear Dr. Quinn: 
You can see the plot of “Number of total objects” and “Number of bright objects” for around 60 first frames as follows:
![1](https://cloud.githubusercontent.com/assets/15619852/16029235/789005f4-31fc-11e6-9bf2-58cb0612bef9.jpg)
There are 2 values for each frame. As you can see, for example in frame 1 we have 2 values: 16 (number of bright objects) and 64 (total number of objects). But the question here is : why the total number of objects in each frame is different from another one? (64, 64, 62, 62,… for frames number 1, 2, 3, 4 , …). The potential reason can be inferred by checking following image:

![2](https://cloud.githubusercontent.com/assets/15619852/16029251/97d29526-31fc-11e6-9a7f-eaf910f3f355.png)

 As you see there are 2 windows. Please ignore the left partial tracking window and just concentrate on right tracking window. The right one is the level in which we’re tracking all the objects. For better tracking of all images I changed the gamma level to make all objects visible and bright. As you can see, there are some frames in which there are 2 or more objects which are intersecting (or seems that interconnecting) together. Thus the tracker is not able to distinguish the objects and as a consequence the number of total objects is varying from a frame to another one. To cope with this problem I switched to another approach and in preprocessing phase, after modifying the gamma level I changed the domain to a gray scale domain and tried to find the edges and subtract the edges from each other. After that the dilate and erode filters has been used and finally the objects separated more from each other and now the total objects are varying in a limited domain ( between 60 – 64 ) but still there are some objects in different frames which are not really separable. 
EDGES OF THE OBJECTS:
![3](https://cloud.githubusercontent.com/assets/15619852/16029268/c6536042-31fc-11e6-941b-5fd9d97d34e7.jpg)

TOTAL OBJECTS AFTER DILATE AND ERODE:
![4](https://cloud.githubusercontent.com/assets/15619852/16029288/e14aeb22-31fc-11e6-840c-e8e469bf2c0a.jpg)

OBJECTS AFTER EDGE SUBTARCTION:
![5](https://cloud.githubusercontent.com/assets/15619852/16029299/f6c4b7b2-31fc-11e6-8e9a-1cc25c8fee87.jpg)

**Comment by magsol** [comment]
Mojtaba, this format is still problematic; even on the UGA network these images are taking a very long time to load. Can you not generate plots or take smaller screenshots?
